### ISSUE TITLE
Removing paramters labeled as 'Questionable'  

### ISSUE THREAD

**Issue by John-R-Wallace-NOAA** [James-Thorson-NOAA/FishLife#13]
I was looking at the M for Atlantic Menhaden (Brevoortia tyrannus) using:
  
    FishLife::Plot_taxa(FishLife::Search_species(Genus='Brevoortia', Species='tyrannus')$match_taxonomy, mfrow = c(2,2))[[1]]$Mean_pred['M']

    Closest match: Actinopterygii_Clupeiformes_Clupeidae_Brevoortia_tyrannus

                       M 
    -0.54480162834710766 

However, looking directly in FishBase_and_RAM:

    (mean_log_M <- FishBase_and_RAM$Y_ij$M[FishBase_and_RAM$Z_ik$Genus %in% 'Brevoortia' & FishBase_and_RAM$Z_ik$Species %in% 'tyrannus'])
     [1]                   NA                   NA                   NA                   NA                   NA
    ...
    [41]  0.00000000000000000 -0.69314718055994529 -0.99425227334386690                   NA

I see that the value of M = 1 ( log(1) = 0 ) which under the growth parameters on FishBase is given a 'Yes' in the 'Questionable' column is included.  

Could those parameters with 'Yes'  in the 'Questionable' column be removed in the future, or at least an argument provided whether or not to include them?

Thanks

**Comment by James-Thorson-NOAA** [comment]
John,

I think you mean to remove data (rather than parameters) that are marked as "Questionable".  In a previous paper (https://doi.org/10.1111/jai.12299) I worked with others to explore options such as this and agree that its a good next step.  Another would be to use the Then et al. database of good M estimates (https://doi.org/10.1093/icesjms/fsu136).  I agree that both would be a good direction to proceed.

Either of these directions would require dedicated funding for student/post-doc or substantial in-kind contributions from NOAA, and I don't plan on doing either as a hobby project.  

Jim

**Comment by John-R-Wallace-NOAA** [comment]
Yes, I meant the data with 'Yes' in the 'Questionable' column.

Thanks for the response Jim.
