### ISSUE TITLE
Mean environmental temp calculation

### ISSUE THREAD

**Issue by seanhardison1** [James-Thorson-NOAA/FishLife#24]
Hello! I was just looking for some more info regarding where mean environmental temperatures are being drawn from for species listed on fishbase (i.e., what's returned by `Plot_taxa()` for matched species). Is this an average over information in the "stocks" table, or something totally different? 

It's unclear to me from reading the fishbase docs where mean environmental temperature comes from. Is it backed out from a regression model somehow?

Thank you

**Comment by James-Thorson-NOAA** [comment]
Yeah, it's temperatures in the Growth table (e.g., pollock [here](https://fishbase.mnhn.fr/popdyn/PopGrowthList.php?ID=1343&GenusName=Pollachius&SpeciesName=virens&fc=183)).  So basically an average of temperature associated with growth studies, rather than a species temperature index (average temperature throughout inferred distribution.  I'd love to discuss by email if you have time and interest to think about ways to get a variety of different temperature metrics included (I've been working on the backburner already with colleagues on the topic)

**Comment by seanhardison1** [comment]
Ah, got it, thank you! Yes I would definitely be interested. I'll follow up with you via email.
